export const SURFACE_FEATURE_BASE_COLOR_TEXTURE = 1;
export const SURFACE_FEATURE_METALLIC_ROUGHNESS_TEXTURE = 2;
export const SURFACE_FEATURE_NORMAL_TEXTURE = 4;
export const SURFACE_FEATURE_EMISSIVE_TEXTURE = 8;
export const SURFACE_FEATURE_TANGENT = 16;
export const SURFACE_FEATURE_OCCLUSION_TEXTURE = 32;
export const SURFACE_FEATURE_STUDIO_ENVIRONMENT = 64;
export const SURFACE_FEATURE_PUNCTUAL_LIGHTS = 128;
export const SURFACE_FEATURE_VIRTUAL_BASE_COLOR_TEXTURE = 256;
export const SURFACE_FEATURE_SPECULAR_TEXTURE = 512;
export const SURFACE_FEATURE_SPECULAR_COLOR_TEXTURE = 1024;
export const SURFACE_FEATURE_SPECULAR_MATERIAL = 2048;
export const SURFACE_FEATURE_LINEAR_OUTPUT = 4096;
export const SURFACE_FEATURE_TRANSMISSION_MATERIAL = 8192;
export const SURFACE_FEATURE_TRANSMISSION_TEXTURE = 16384;
export const SURFACE_FEATURE_THICKNESS_TEXTURE = 32768;
export const SURFACE_FEATURE_PREFILTERED_ENVIRONMENT = 65536;
export const SURFACE_FEATURE_VERTEX_COLOR = 131072;
export const SURFACE_FEATURE_IDENTITY_TEXTURE_COORDINATES = 262144;
export const SURFACE_FEATURE_ROTATED_ENVIRONMENT = 524288;
export const SURFACE_FEATURE_DIRECTIONAL_LIGHTS = 1048576;

export const SURFACE_TEXTURE_FEATURES = SURFACE_FEATURE_BASE_COLOR_TEXTURE
  | SURFACE_FEATURE_METALLIC_ROUGHNESS_TEXTURE
  | SURFACE_FEATURE_NORMAL_TEXTURE
  | SURFACE_FEATURE_EMISSIVE_TEXTURE
  | SURFACE_FEATURE_OCCLUSION_TEXTURE
  | SURFACE_FEATURE_SPECULAR_TEXTURE
  | SURFACE_FEATURE_SPECULAR_COLOR_TEXTURE
  | SURFACE_FEATURE_TRANSMISSION_TEXTURE
  | SURFACE_FEATURE_THICKNESS_TEXTURE
  | SURFACE_FEATURE_VIRTUAL_BASE_COLOR_TEXTURE;
